#!/bin/sh

# Other commands

# Add the following lines to configure Nginx access log
mkdir -p /var/log/nginx
touch /var/log/nginx/access.log
chmod 0644 /var/log/nginx/access.log
ln -sf /dev/stdout /var/log/nginx/access.log

# Start Nginx
exec nginx -g "daemon off;"

