name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Nginx version from Docker image
        id: get-version
        run: |
          VERSION=$(docker run --rm aaronlee/nginx-extras:latest cat /tmp/nginx_version.txt)
          echo "::set-output name=version::$VERSION"

      - name: Get Nginx version from version file
        id: get-version-file
        run: |
          VERSION_FILE=$(cat version)
          echo "::set-output name=version-file::$VERSION_FILE"

      - name: Check if versions match
        id: check-versions
        run: |
          if [ "${{ steps.get-version.outputs.version }}" == "${{ steps.get-version-file.outputs.version-file }}" ]; then
            echo "Versions match. No need to push to Docker Hub."
            exit 0
          else
            echo "Versions do not match. Proceeding with Docker image build and push."
            exit 1
          fi

      - name: Build nginx-extras:latest image
        if: steps.check-versions.outcome == 'failure'
        run: docker build -t aaronlee/nginx-extras:latest .

      - name: Set build timestamp
        if: steps.check-versions.outcome == 'failure'
        id: set-timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push Docker image
        if: steps.check-versions.outcome == 'failure'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-extras:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-extras:${{ steps.get-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-extras:${{ steps.get-version.outputs.version }}-${{ steps.set-timestamp.outputs.timestamp }}
