name: 构建并推送用于进行版本对比的 Docker 镜像

on:
  push:
    branches:
      - main
  schedule:
      - cron: "33 2 26 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      DOCKER_TAG_TEST: ${{ secrets.DOCKER_TAG_TEST }}

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 登录 Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME_TEST }}" -p "${{ secrets.DOCKER_ACCESS_TOKEN_TEST }}"

    - name: 构建用于进行版本对比的镜像
      run: |
        docker buildx build --platform linux/amd64 -t "${{ secrets.DOCKER_USERNAME_TEST }}/${{ secrets.DOCKER_IMAGE_TEST }}:${{ env.DOCKER_TAG_TEST }}" --no-cache --push .

    - name: 将运行时间推送更新到 GitHub
      run: |
        echo $(date +"%Y-%m-%d %H:%M:%S") > time
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add time
        current_time=$(TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M:%S")
        git commit -m "运行时间 - 北京时间: $current_time"
        git push origin main
